apiVersion: v1
kind: Pod
metadata:
  name: mlflow-server
  labels:
    app.kubernetes.io/name: mlflow-server
spec:
  containers:
  - name: mlflow-server
    image: ghcr.io/mlflow/mlflow:v2.22.0
    args: ["mlflow", "server"]  
    ports:
      - containerPort: 5000
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server-service
spec:
  selector:
    app.kubernetes.io/name: mlflow-server
  ports:
  - name: mlflow-server-service
    protocol: TCP
    port: 5000
    targetPort: http-web-svc